version: 2
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello" > foo.txt
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/test-results
      - store_artifacts:
          path: build/reports/lint-results.html
      - store_test_results:
          path: build/reports

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
